### ISSUE TITLE
Unwanted string at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nerzhul/ncsms-android#202]
Following string should not be imported and listed at Transifex:

https://github.com/nerzhul/ownCloud-SMS-App/blob/8a628abb2918e5d04f1a478a951f0e781b0bb6ed/src/main/res/values/strings.xml#L45

Please adapt your sync to Transifex.

Reported at Transifex.

**Comment by nerzhul** [comment]
Hello, thanks for the report

**Comment by rakekniven** [comment]
Hello @nerzhul Any change you can fix this?

**Comment by nerzhul** [comment]
done :) sorry for the delay
