### ISSUE TITLE
Obselete string. Not needed when working with Transifex

### ISSUE THREAD

**Issue by rakekniven** [nerzhul/ncsms-android#206]
Please remove following string from Transifex.

https://github.com/nerzhul/ncsms-android/blob/9409ca64e205409a6c740e72e1866b8eeab55cee/src/main/res/values/google_playstore_strings.xml#L32

Reported at Transifex.

**Comment by nerzhul** [comment]
solved

**Comment by rakekniven** [comment]
For the records. Commit:

https://github.com/nerzhul/ncsms-android/commit/d92ed7d4b1948638f74794f097950935b506753a
